Please see the corresponding writeup here:
    http://kawahara.ca/how-to-normalize-vectors-to-unit-norm-in-python/

In [1]:
import numpy as np
from sklearn import preprocessing

# 2 samples, with 3 dimensions.
# The 2 rows indicate 2 samples.
# The 3 columns indicate 3 features for each sample.
X = np.asarray([
[-1,0,1],
[0,1,2]],
dtype=np.float) # Float is needed.

# Before-normalization.
print(X)
# Output,
# [[-1.  0.  1.]
#  [ 0.  1.  2.]]

[[-1.  0.  1.]
 [ 0.  1.  2.]]


/tmp/ipykernel_4561/2698447323.py:10: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.float) # Float is needed.


<h1>L2 Normalization</h1>

In [2]:
# l2-normalize the samples (rows).
X_normalized = preprocessing.normalize(X, norm='l2')

# After normalization.
print(X_normalized)
# Output,
# [[-0.70710678  0.          0.70710678]
#  [ 0.          0.4472136   0.89442719]]

[[-0.70710678  0.          0.70710678]
 [ 0.          0.4472136   0.89442719]]


In [3]:
# Square all the elements/features.
X_squared = X_normalized ** 2
print(X_squared)
# Output,
# [[ 0.5  0.   0.5]
#  [ 0.   0.2  0.8]]

# Sum over the rows.
X_sum_squared = np.sum(X_squared, axis=1)
print(X_sum_squared)
# Output,
# [ 1.  1.]

# Yay! Each row sums to 1 after being normalized.

[[0.5 0.  0.5]
 [0.  0.2 0.8]]
[1. 1.]


<h1>L1 normalization</h1>

In [4]:
X_normalized_l1 = preprocessing.normalize(X, norm='l1')
print(X_normalized_l1)
# [[-0.5   0.   0.5]
#  [  0.   0.3  0.67]]

[[-0.5         0.          0.5       ]
 [ 0.          0.33333333  0.66666667]]


In [5]:
# Absolute value of all elements/features.
X_abs = np.abs(X_normalized_l1)
print(X_abs)
# [[0.5   0.   0.5]
#  [0     0.3  0.67]]

[[0.5        0.         0.5       ]
 [0.         0.33333333 0.66666667]]


In [6]:
# Sum over the rows.
X_sum_abs = np.sum(X_abs, axis=1)
print(X_sum_abs)
# Output,
# [ 1.  1.]

# Yay! Each row sums to 1 after being normalized.

[1. 1.]
